local logos = {
  "af_camel",
  "af_clouds",
  "af_curtain",
  "af_cycling",
  "af_dragon_worm",
  "af_echidna1",
  "af_echidna2",
  "af_flamingo",
  "af_grin",
  "af_lighthouse",
  "af_lunar_landing",
  "af_lunch_break",
  "af_records",
  "af_rocket",
  "af_sleep",
  "af_slope",
  "af_space",
  "af_summer_rain",
  "af_the_witch",
  "af_three_little_pigs",
  "af_trex",
  "af_winter_moon",
  "bamdad_crazy",
  "bamdad_doom",
  "bamdad_slant",
  "book1",
  "book2",
  "bridge",
  "cat1",
  "cat2",
  "cat3",
  "chocolate",
  "commodore",
  "country_afghanistan",
  "dog1",
  "dragon1",
  "fairy1",
  "fairy2",
  "fish1",
  "fish2",
  "jonquille",
  "lazyvim",
  "partition",
  "pinocchio",
  "pissenlit1",
  "pissenlit2",
  "quake1",
  "quake2",
  "reaper",
  "sleep",
  "snoopy1",
  "snoopy2",
  "spider1",
  "tournesol",
  "trumpet",
  "woman_by_the_sea",
  "ziggurat",
}

math.randomseed(os.time())
local random_logo = logos[math.random(#logos)]
local logo = require("logos." .. random_logo)
local normalize_logo = require("utils.normalize_logo")
logo = normalize_logo(logo)
return logo
